top/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('post/<slug>/', views.post_detail, name='post_detail'),
    path('post_create/', views.post_create, name='post_create'),
    path('post_delete/<slug>', views.post_delete, name='post_delete'),
    path('post_edit/<slug>', views.post_edit, name='post_edit'),
    path('<slug>/like', views.like, name='like'),
    path('<slug>/dislike', views.dislike, name='dislike'),
    path('<int:pk>/delete', views.delete_comment, name='delete_comment'),
    path('<int:pk>/edit', views.edit_comment, name='edit_comment')
]

top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'top'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

top/users/urls.py
from django.urls import path
from  . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out')
]

top/blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    date = models.DateField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    thumb = models.ImageField(default='image.jpg', blank=True)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')

    def __str__(self):
        return self.title

    def snippet(self):
        return f"{self.text[:20]}...read more"

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()


class Person(models.Model):
    name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Article, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post} - {self.body[:5]}"

top/blog/forms.py
from django import forms
from . import models


class ArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))
    text = forms.CharField(widget=forms.TextInput(attrs={'class': 'textarea', 'size': '40'}))
    slug = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}))

    class Meta:
        model = models.Article
        fields = ['title', 'text', 'slug', 'thumb']


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'textarea',
            'size': '40',
            'placeholder': 'Напишите комментарий здесь...'
        }
    ))

    class Meta:
        model = models.Comment
        fields = ['body',]

top/blog/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from . import forms
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator


# Create your views here.
@login_required(login_url='/users/sign_in')
def home(request):
    search = request.GET.get('search')
    articles = Article.objects.all().order_by('-date')
    pages = Paginator(articles, 3)
    page = request.GET.get('page')
    articles = pages.get_page(page)
    articles = articles.filter(Q(title__icontains=search) | Q(text__icontains=search)) if search else articles
    return render(request, 'home.html', {'articles': articles})


@login_required(login_url='/users/sign_in')
def post_detail(request, slug):
    post = Article.objects.get(slug=slug)
    form = forms.CommentForm(request.POST or None)
    post_comments = post.comment_set.all()
    pages = Paginator(post_comments, 3)
    page = request.GET.get('page')
    post_comments = pages.get_page(page)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.post = post
        instance.save()
        return redirect('blog:post_detail', slug=post.slug)
    return render(request, 'post.html', {'post': post, 'form': form, 'post_comments': post_comments})


@login_required(login_url='/users/sign_in')
def post_create(request):
    if request.method == 'POST':
        form = forms.ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('blog:home')
    form = forms.ArticleForm()
    return render(request, 'article_create.html', {'form': form})


@login_required(login_url='/users/sign_in')
def post_delete(request, slug):
    post = Article.objects.get(slug=slug)
    if request.user != post.author:
        return render(request, 'error.html', {'post': post, 'delete': True})
    if request.method == 'POST':
        post.delete()
        return redirect('blog:home')
    return render(request, 'post_delete.html', {'post': post})


@login_required(login_url='/users/sign_in')
def post_edit(request, slug):
    post = Article.objects.get(slug=slug)
    if request.user != post.author:
        return render(request, 'error.html', {'post': post, 'edit': True})
    if request.method == 'POST':
        form = forms.ArticleForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:post_detail', slug=request.POST.get('slug'))
    form = forms.ArticleForm(instance=post)
    return render(request, 'post_edit.html', {'form': form, 'post': post})


@login_required(login_url='/users/sign_in')
def like(request, slug):
    post = Article.objects.get(slug=slug)
    if request.user == post.author:
        return render(request, 'error.html', {'like': True, 'post': post})
    if request.user not in post.likes.all():
        post.likes.add(request.user)
        post.dislikes.remove(request.user)
    elif request.user in post.likes.all():
        post.likes.remove(request.user)
    return redirect('blog:post_detail', slug=slug)


@login_required(login_url='/users/sign_in')
def dislike(request, slug):
    post = Article.objects.get(slug=slug)
    if request.user == post.author:
        return render(request, 'error.html', {'dislike': True, 'post': post})
    if request.user not in post.dislikes.all():
        post.dislikes.add(request.user)
        post.likes.remove(request.user)
    elif request.user in post.dislikes.all():
        post.dislikes.remove(request.user)
    return redirect('blog:post_detail', slug=slug)


def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.user != comment.user:
        return render(request, 'restrict.html', {'delete': True, 'post': comment.post})
    if request.method == 'POST':
        comment.delete()
        return redirect('blog:post_detail', slug=comment.post.slug)
    return render(request, 'delete_comment.html', {'post': comment.post})


def edit_comment(request, pk):
    comment = Comment.objects.get(pk=pk)
    if request.user != comment.user:
        return render(request, 'restrict.html', {'edit': True, 'post': comment.post})
    if request.method == 'POST':
        form = forms.CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
        return redirect('blog:post_detail', slug=comment.post.slug)
    form = forms.CommentForm(instance=comment)
    return render(request, 'edit_comment.html', {'form': form, 'post': comment.post})

top/blog/templates/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

<form action="{% url 'blog:post_create' %}" class="site-form has-background-light" enctype="multiplate/form-data"
method="post">
    {% csrf_token %}
    {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field }}
            </div>
        {% endfor %}
    <div class="has-text-centered my-2">
        <button type="submit" class="button is-success">Опубликовать</button>
        <a href="{% url 'blog:home' %}" class="button is-danger">
            Назад
        </a>
    </div>
{% endblock %}

top/blog/templates/base_layout.html
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
<section class="hero is-fullheight">
    {% if user.is_authenticated %}
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item" href="{% url 'blog:home' %}">
                        <img src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                </div>
                <div class="navbar-start">
                   <span class="navbar-item">
                       <a href="{% url 'blog:post_create' %}" class="button is-info is-outlined">
                           <span class="mr-2">
                               <ion-icon name="book-outline"></ion-icon>
                           </span>
                           <span>
                               Создать пост
                           </span>
                       </a>
                   </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                         <a class="navbar-item my-4 mx-1 button is-light">
                            Добро пожаловать: {{ user }}
                        </a>
                        <span class="navbar-item">
                            <a class="button is-warning" href="{% url 'users:sign_out' %}">
                                Выйти
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </header>
    </div>
    {% endif %}

    <div class="hero-body">
        <div class="container has-text-centered">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    </div>
</section>
</body>

</html>

top/blog/templates/delete_comment.html
{% extends 'base_layout.html' %}

{% block content %}

    <form method="post" class="site-form has-background-light">
        {% csrf_token %}
        <div class="content is-size-4 mb-4">
            Вы действительно хотите удалить комментарий?
        </div>
        <div class="has-text-centered">
            <button type="submit" class="button is-success">Удалить</button>
            <a href="{% url 'blog:post_detail' post.slug %}" class="button is-warning">
                Вернуться к посту
            </a>
        </div>
    </form>

{% endblock %}

top/blog/templates/edit_comment.html
{% extends 'base_layout.html' %}

{% block content %}

    <form method="post" enctype="multipart/form-data" class="comment site-form has-background-light">
    <div class="title">Отредактировать комментарий</div>
        {% csrf_token %}
        {{ form }}
        <div class="has-text-centered my-2">
            <button type="submit" class="button is-success">Отправить</button>
            <a href="{% url 'blog:post_detail' post.slug %}" class="button is-warning">
                Назад
            </a>
        </div>
    </form>

{% endblock %}

top/blog/templates/error.html
{% load static from static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
</head>
<body>
<section class="hero has-background-info is-fullheight">
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a href="{% url 'blog:home' %}" class="navbar-item">
                        <img src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg" alt="">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                </div>
            </div>
        </header>

    </div>
    <div class="hero-body">
        <div class="columns is-centered">
            <div class="column is-6">
                <div class="box has-text-centered">
                    <div class="title">
                        Вы не можете
                        {% if edit %}
                            отредактировать
                        {% endif %}
                        {% if delete %}
                            удалить
                        {% endif %}
                        {% if edit or delete %}
                            данный пост, так как не являетесь автором
                        {% endif %}
                        {% if like %}
                            поставить лайк
                        {% endif %}
                        {% if dislike %}
                            поставить дизлайк
                        {% endif %}
                        {% if like or dislike %}
                            своему посту
                        {% endif %}
                    </div>
                    <div class="buttons is-grouped is-centered">
                        <a href="{% url 'blog:post_detail' post.slug %}" class="button is-success">
                            Назад
                        </a>
                        <a href="{% url 'blog:home' %}" class="button is-warning">
                            Вернуться на главную
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
</body>
</html>

top/blog/templates/home.html
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bulma.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
<section class="hero is-fullheight ny">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
        <header class="navbar">
            <div class="container">
                <div class="navbar-brand">
                    <a class="navbar-item">
                        <img src="https://msk.top-academy.ru/dist/images/logo/step_logo_rus.svg" alt="Logo">
                    </a>
                    <span class="navbar-burger" data-target="navbarMenuHeroC">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                </div>
                <div class="navbar-start">
                   <span class="navbar-item">
                       <a href="{% url 'blog:post_create' %}" class="button is-text is-medium">
                           <span class="mr-2">
                               <ion-icon name="book-outline"></ion-icon>
                           </span>
                           <span>
                               Создать пост
                           </span>
                       </a>
                   </span>
                </div>
                <div id="navbarMenuHeroC" class="navbar-menu">
                    <div class="navbar-end">
                        <form action="{% url 'blog:home' %}" method="get">
                            <div class="field has-addons mt-4 mr-2">
                                <div class="control">
                                    <input type="search" class="input" placeholder="Поиск постов" name="search">
                                </div>
                                <div class="control">
                                    <button type="submit" class="button is-light">
                                        <ion-icon name='search-outline'></ion-icon>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <a class="navbar-item my-4 mx-1 button is-light">
                            Добро пожаловать: {{ user }}
                        </a>
                        <span class="navbar-item">
                            <a class="button is-warning" href="{% url 'users:sign_out' %}">
                                Выйти
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="columns is-centered">
                <div class="column is-7" style="margin-left: 350px;">
                    <div class="title is-3">
                        Академия ТОП от всего сердца поздравляет вас с Новым годом! Желаем, всего самого доброго,
                        светлого и прекрасного. Пусть исполняются самые заветные желания. Пусть Новый 2023 год
                        станет самым ярким, успешным и счастливым!
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

<section class="section has-background-info-light">
    <div class="container">
        <div class="title is-2 has-text-centered my-6">
            Читайте наши посты
        </div>
        <div class="columns is-centered is-multiline">
            {% for article in articles %}
                <div class="column is-3">
                    <div class="card has-text-centered">
                        <a href="{% url 'blog:post_detail' article.slug %}">
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-content">
                                        <div class="title has-text-black is-2">
                                            {{ article }}
                                        </div>
                                        <div class="subtitle is-6 has-text-grey">
                                            {% if user == article.author %}
                                                Опубликовано вами
                                            {% else %}
                                                Опубликовано {{ article.author }}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="content">
                                    {{ article.snippet }}
                                    <br>
                                    <br>
                                    <div>{{ article.date }}</div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

        {#        {{ articles }}#}
        {#        <br>#}
        {#    Предыдущая страница: {{ articles.has_previous }}#}
        {#        <br>#}
        {#    Следующая страница: {{ articles.has_next }}#}
        {#        <br>#}
        {#    Текущая страница: {{ articles.number }}#}
        {#        <br>#}
        {#    Количество страниц: {{ articles.paginator.num_pages }}#}

        {#        {% if articles.has_previous %}#}
        {#            <a href="?page=1">&laquo; Первая страница</a>#}
        {#            <a href="?page={{ articles.previous_page_number }}">Назад</a>#}
        {#        {% endif %}#}
        {#        Страница: {{ articles.number }}#}
        {#        из {{ articles.paginator.num_pages }}#}
        {#        {% if articles.has_next %}#}
        {#            <a href="?page={{ articles.next_page_number }}">Далее</a>#}
        {#            <a href="?page={{ articles.paginator.num_pages }}">В конец</a>#}
        {#        {% endif %}#}

        <nav role="navigation" class="pagination is-centered my-6" aria-label="pagination">
            {% if articles.has_previous %}
                <a class="pagination-previous" href="?page={{ articles.previous_page_number }}">Назад</a>
            {% endif %}
            {% if articles.has_next %}
                <a class="pagination-next" href="?page={{ articles.next_page_number }}">Далее</a>
            {% endif %}
            <ul class="pagination-list">
                <li>
                    <a class="pagination-link is-current" aria-label="{{ articles.number }}" aria-checked="page">
                        {{ articles.number }}
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</section>
</body>
</html>

top/blog/templates/post.html
{% extends 'base_layout.html' %}
{% load static from static %}

{% block content %}

    <div class="box" style="min-width: 100%">
        {% if user == post.author %}
            <div class="has-text-right">
                <a href="{% url 'blog:post_edit' post.slug %}" class="button is-info">
                    <ion-icon name="create-outline"></ion-icon>
                </a>
                <a href="{% url 'blog:post_delete' post.slug %}" class="button is-danger">
                    <ion-icon name="trash-outline"></ion-icon>
                </a>
            </div>
        {% else %}
            <div class="has-text-right content has-text-grey-light">
                Пост доступен только для чтения
            </div>
        {% endif %}
        <div class="title has-text-black has-text-centered">
            {{ post }}
        </div>
        <img src="{{ post.thumb.url }}" alt="" class="image is-centered" style="min-width: 100%; border-radius: 5px">
        <div class="subtitle has-text-black has-text-centered my-5">
            {{ post.text }}
        </div>
        <div class="columns">
            <div class="column is-1">
                <form action="{% url 'blog:like' post.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    {% if post.author != user %}
                        {% if user not in post.likes.all %}
                            <button type="submit" class="button">
                        {% else %}
                            <button type="submit" class="button is-success">
                        {% endif %}
                    {% else %}
                        <button type="submit" class="button" disabled>
                    {% endif %}
                    <ion-icon name="thumbs-up-outline"></ion-icon>
                    <span class="ml-2">
                    {{ post.total_likes }}
                </span>
                    </button>
                </form>
            </div>
            <div class="column is-1">
                <form action="{% url 'blog:dislike' post.slug %}" method="post" class="has-text-right">
                    {% csrf_token %}
                    {% if post.author != user %}
                        {% if user not in post.dislikes.all %}
                            <button type="submit" class="button">
                        {% else %}
                            <button type="submit" class="button is-danger">
                        {% endif %}
                    {% else %}
                        <button type="submit" class="button" disabled>
                    {% endif %}
                    <ion-icon name="thumbs-down-outline"></ion-icon>
                    <span class="ml-2">
                    {{ post.total_dislikes }}
                </span>
                    </button>
                </form>
            </div>
        </div>

        {% if not post.comment_set.all %}
            <div class="has-text-centered has-text-grey-light is-size-5 mx-3">
                Пока нет комментариев
            </div>
        {% else %}
            <p class="has-text-centered is-size-3 mb-6">
            <div class="columns is-centered is-multiline">
                {% for comment in post_comments %}
                    <div class="column is-4">
                        <article class="message is-info">
                            <div class="message-header">
                                {% if request.user == comment.user %}
                                    Оставлено Вами {{ comment.date }}
                                {% else %}
                                    Оставлено {{ comment.user }} {{ comment.date }}
                                {% endif %}
                                {% if request.user == comment.user %}
                                    <div class="has-text-right is-size-5">
                                        <a style="text-decoration: none"
                                           href="{% url 'blog:edit_comment' comment.pk %}"
                                           class="button is-info">
                                            <ion-icon name='create-outline'></ion-icon>
                                        </a>
                                        <a style="text-decoration: none"
                                           href="{% url 'blog:delete_comment' comment.pk %}"
                                           class="button is-info">
                                            <ion-icon name='trash-outline'></ion-icon>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="message-body">
                                {{ comment.body }}
                            </div>
                        </article>
                    </div>
                {% endfor %}
            </div>
            </p>
        {% endif %}

        <nav role="navigation" class="pagination is-centered my-6" aria-label="pagination">
            {% if post_comments.has_previous %}
                <a class="pagination-previous" href="?page={{ post_comments.previous_page_number }}">Назад</a>
            {% endif %}
            {% if post_comments.has_next %}
                <a class="pagination-next" href="?page={{ post_comments.next_page_number }}">Далее</a>
            {% endif %}
            <ul class="pagination-list">
                <li>
                    <a class="pagination-link is-current" aria-label="{{ post_comments.number }}" aria-checked="page">
                        {{ post_comments.number }}
                    </a>
                </li>
            </ul>
        </nav>

        <div class="has-text-grey is-size-6 has-text-right is-italic">
            <div class="datetime">
                Дата публикации: {{ post.date }}
            </div>
            <div class="content">
                {% if user == post.author %}
                    Опубликовано вами
                {% else %}
                    Опубликовано "{{ post.author }}"
                {% endif %}
            </div>
        </div>
        <form class="comment" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="button is-success is-fullwidth my-3">
                Отправить
            </button>
        </form>
    </div>
{% endblock %}

top/blog/templates/post_delete.html
{% extends 'base_layout.html' %}
{% block content %}

<form method="post" class="site-form has-background-light" p-6>
    {% csrf_token %}
    <p class="subtitle has-text-centered is-4 my-4">
        Вы действительно хотите удалить пост "{{ post }}"?
        <br><br>
        <button type="submit" class="button is-success">Да</button>
        <a href="{% url 'blog:post_detail' post.slug %}" class="button is-warning">
            Вернуться к посту
        </a>
    </p>
</form>

{% endblock %}



top/blog/templates/post_edit.html
{% extends 'base_layout.html' %}
{% block content %}

<form class="site-form has-background-light" enctype="multiplate/form-data"
method="post">
    {% csrf_token %}
    {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field }}
            </div>
        {% endfor %}
    <div class="has-text-centered my-2">
        <button type="submit" class="button is-success">Опубликовать</button>
        <a href="{% url 'blog:post_detail' post.slug %}" class="button is-danger">
            Назад
        </a>
    </div>
</form>
{% endblock %}