top/top/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'top'), namespace='blog')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

top/users/urls.py
from django.urls import path
from  . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out')
]

top/users/models.py
from django.db import models

# Create your models here.

top/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'label': 'Придумате никнейм'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'label': 'Придумайте пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'label': 'Повторите пароль'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'label': 'Напишите никнейм'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input', 'label': 'Напишите пароль'}))

    class Meta:
        model = User
        fields = ['username', 'password']

top/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from .forms import SignUpForm, SignInForm


# Create your views here.

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:sign_in')
    form = SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('blog:home')
    form = SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')

top/users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block content %}

    <form method="post" class="site-form has-text-centered has-background-light">
        <div class="title is-2">
            Вход
        </div>
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="button is-success is-fullwidth mt-4">
            Войти
        </button>
        <p class="has-text-centered has-text-grey-light mt-4">
            Нет аккаунта?
        </p>
        <a href="{% url 'users:sign_up' %}">
            Перейти на страницу регистрации
        </a>
    </form>

{% endblock %}

top/users/templates/sign_up.html
{% extends 'base_layout.html' %}

{% block content %}

    <form method="post" class="site-form has-background-light">
        <div class="title is-2 has-text-centered has-text-grey">
            Регистрация
        </div>
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                {{ field }}
            </div>
        {% endfor %}
        <button type="submit" class="button is-success is-fullwidth my-3">
            Зарегистрироваться
        </button>
        <p class="has-text-centered has-text-grey-light mt-2">
            Уже есть аккаунт?
            <br>
            <a href="{% url 'users:sign_in' %}">
                Перейти на страницу входа
            </a>
        </p>
    </form>

{% endblock %}